package com.concordia.comp6421.compiler.lexicalAnalyzer.entity;

public enum TokenType {
    INTEGER, FLOAT, IDENTIFIER, ERROR,

    EQEQ, LTGT, LT, GT,LEQ, GEQ,
    SEMICOLON, COMMA, DOT, COLON, COLONCOLON,

    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION,
    EQ, ANDAND, EXCLAMATION, OROR, EXP,

    LP, RP, LCP, RCP, LSP, RSP,
    SLASHSTAR,STARSLASH,SLASHSLASH,

    IF, THEN, ELSE, FOR, CLASS,
    READ, WRITE, RETURN, MAIN,
}
